---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mwiki-configmap
data:
  database: postgres
  database_uri: http://localhost:5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki-with-configmap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediawiki
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
      - name: mediawiki
        image: mediawiki:latest
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: mwiki-configmap
              key: database
        - name: POSTGRES_URI
          valueFrom:
            configMapKeyRef:
              name: mwiki-configmap
              key: database_uri
        ports:
        - containerPort: 80